production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gurmap_dev
  pool: 5
  username: root
  password: 
  host: localhost

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gurmap_dev
  pool: 5
  username: root
  password: 
  host: localhost

